// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCheckbox: typeof import('@layui/layui-vue')['LayCheckbox']
    LayCol: typeof import('@layui/layui-vue')['LayCol']
    LayConfigProvider: typeof import('@layui/layui-vue')['LayConfigProvider']
    LayDatePicker: typeof import('@layui/layui-vue')['LayDatePicker']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayEmpty: typeof import('@layui/layui-vue')['LayEmpty']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayFullscreen: typeof import('@layui/layui-vue')['LayFullscreen']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayIcon: typeof import('@layui/icons-vue')['LayIcon']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayLine: typeof import('@layui/layui-vue')['LayLine']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayPage: typeof import('@layui/layui-vue')['LayPage']
    LayRow: typeof import('@layui/layui-vue')['LayRow']
    LayScroll: typeof import('@layui/layui-vue')['LayScroll']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTab: typeof import('@layui/layui-vue')['LayTab']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTag: typeof import('@layui/layui-vue')['LayTag']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    LayTree: typeof import('@layui/layui-vue')['LayTree']
    LayUpload: typeof import('@layui/layui-vue')['LayUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
